version: "2.2"

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: test-task/database
    container_name: database
    depends_on:
      - postgres
    volumes:
      - ./database:/src/test-task/database
      - database_node_modules:/src/test-task/database/node_modules
    command: yarn run dev
    env_file:
      - database/.env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: test-task/server
    container_name: server
    depends_on:
      - database
    ports:
      - "8080:2000"
    volumes:
      - ./server:/src/test-task/server
      - server_node_modules:/src/test-task/server/node_modules
    command: yarn run dev
    env_file:
      - server/.env

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  database_node_modules:
    name: test-task-database-nm
  server_node_modules:
    name: test-task-server-nm
  postgres_data:
    name: test-task-postgres-data

networks:
  default:
    name: test-task
